# Generated by Django 3.2.4 on 2021-08-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'session_key')},
        ),
    ]
